version: "3.9"

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    environment:
      - API_TOKEN=${API_TOKEN}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
